import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// BackgroundRemover — generated by AppFactoryKit appgen from niche "background-remover".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum BackgroundRemoverFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "BackgroundRemover",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "wand.and.stars",
                          title: "BackgroundRemover",
                          message: "Remove/replace photo backgrounds."),
                    .init(systemImage: "photo.on.rectangle.angled",
                          title: "Go Pro",
                          message: "HD export, batch, brand backgrounds.")
                ],
                presentsPaywallOnFinish: true,
                accent: .purple
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock BackgroundRemover Pro",
                subheadline: "HD export, batch, brand backgrounds.",
                benefits: [
                    .init(systemImage: "infinity", title: "HD export"),
                    .init(systemImage: "bolt.fill", title: "Batch"),
                    .init(systemImage: "nosign", title: "Brand backgrounds")
                ],
                productIDs: ["background-remover_yearly", "background-remover_weekly"],
                highlightedProductID: "background-remover_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .purple, heroSystemImage: "wand.and.stars")
            )
        )
        return AppFactory(config)
    }
}

@main
struct BackgroundRemoverApp: App {
    @StateObject private var factory = BackgroundRemoverFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.purple)
        }
    }
}
